CREATE DATABASE doingsdone_10_2019
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;


USE doingsdone_10_2019;

CREATE TABLE project (
id INT AUTO_iNCREMENT PRIMARY KEY,
name VARCHAR(128),
user_id INT
);

CREATE TABLE task (
id INT AUTO_iNCREMENT PRIMARY KEY,
project_id INT,
user_id INT,
date_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
is_complete BOOL DEFAULT FALSE,
name VARCHAR(128) NOT NULL,
file_path VARCHAR(128),
date_complete TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE user (
id INT AUTO_iNCREMENT PRIMARY KEY,
date_create_acc TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
name VARCHAR(128),
pass varchar (255),
);
